# Generated by Django 5.1.3 on 2024-11-27 15:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('date_time_start', models.DateTimeField()),
                ('date_time_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('venue_details', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
