# Generated by Django 5.1.3 on 2024-11-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
